In [3]:
import pandas as pd
import numpy as np
from functools import reduce

#data movies rotten tomatoes
data = pd.read_csv('rotten_tomatoes_movies.csv', usecols=[1,6,7,8,9,13,15,18])
#rename columns for first dataset
data.columns = ['title', 'genre', 'directors','writers','actors','studio_name','tomato_rating','audience_rating']
#dataset that contains budget
dataBudget = pd.read_csv('budget.csv', usecols=[0,1,6])
dataBudget.columns = ['budget', 'genres' , 'title']
#dataBudget.head(10)

#list of datasets
dfs = [data, dataBudget]
#merging the movies dataset with the budget dataset based on title
df_final = reduce(lambda left,right: pd.merge(left,right,on='title'), dfs)

#data: (title, genre, directors, writers, actors, studio name) labels: (tomoto_rating, audience rating, budget)
df_final = df_final.dropna()  #3920 before dropping null values -> 3830 after dropping those values
#df_final.shape
df_final.head()

title  \
0  Percy Jackson & the Olympians: The Lightning T...   
1                                        Please Give   
2                                       3:10 to Yuma   
3                                       3:10 to Yuma   
4                                         Dark Water   

                                               genre          directors  \
0  Action & Adventure, Comedy, Drama, Science Fic...     Chris Columbus   
1                                             Comedy  Nicole Holofcener   
2                           Classics, Drama, Western       Delmer Daves   
3                 Action & Adventure, Drama, Western      James Mangold   
4  Art House & International, Horror, Mystery & S...       Hideo Nakata   

                                             writers  \
0                                       Craig Titley   
1                                  Nicole Holofcener   
2                                     Halsted Welles   
3         Derek Haas, Halsted Welles, Michael Brandt   
4  Hideo Hakata, Takashige Ichise, Yoshihiro Naka...   

                                              actors             studio_name  \
0  Logan Lerman, Brandon T. Jackson, Alexandra Da...        20th Century Fox   
1  Catherine Keener, Amanda Peet, Oliver Platt, R...  Sony Pictures Classics   
2  Glenn Ford, Van Heflin, Felicia Farr, Leora Da...       Columbia Pictures   
3  Russell Crowe, Christian Bale, Logan Lerman, D...         Lionsgate Films   
4  Hitomi Kuroki, Rio Kanno, Shigemitsu Ogi, Mire...        Toho Company Ltd   

   tomato_rating  audience_rating    budget  \
0             49             53.0  95000000   
1             86             64.0   3000000   
2             96             78.0  55000000   
3             89             86.0  55000000   
4             80             66.0  30000000   

                                              genres  
0  [{"id": 12, "name": "Adventure"}, {"id": 14, "...  
1  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...  
2                    [{"id": 37, "name": "Western"}]  
3                    [{"id": 37, "name": "Western"}]  
4  [{"id": 18, "name": "Drama"}, {"id": 27, "name...

In [4]:
#iterate through the actors column and split them by the ',' and put them in a list

#fastest way to get length
actorsLen = len(df_final.index) #3

#splitting cells into multiple lists
actorsList = df_final.actors.str.split(', ')

#create a list where actors will be stored
listOfActors = []

#ITERATE THROUGH ONE LIST
#for i in range(len(actorsList[0])):
    #txt = actorsList[0][i].split(', ')
    #print(txt)
   
    #Working --> adding actors
for i in range(len(actorsList)):
    try:
        for j in range(len(actorsList[i])):
            txt = actorsList[i][j].split(', ')
            #print(i)
            listOfActors += txt
            #print(txt)
    except KeyError:
        continue
                
#removing duplicates from listOfActors
setOfActors = list(set(listOfActors))

#len(listOfActors) #-> 141445
#len(setOfActors) #-> 82184

In [5]:
#json dataframe of actors and rating
import json
df_jsonActors = pd.read_json('actors.json')
jsonElem = df_jsonActors.assign(results = df_jsonActors.apply(lambda x: [x[['name','rating']].to_dict()], axis=1)).drop(['image_path','alternative_name','objectID', 'results'], axis=1).to_dict(orient='records')
len(jsonElem)

jsonElem[0]

#for i in range(len(jsonElem)):
   # if(jsonElem[i]['name'] == setOfActors[i]):
     #   print(jsonElem[i]['name'])
   #else:
        #print('not found')
counter = 0
actorsAndRating = []
#Iterating through setOfActors and JSON actors and try to find them - 
for i in range(len(setOfActors)):
    for j in range(len(jsonElem)):
        if(jsonElem[j]['name'] == setOfActors[i]):
            print(jsonElem[j])
            actorsAndRating.append(jsonElem[j])
            counter +=1
            print(counter)

#jsonElem[0]['rating']

{'name': 'Mark Hamill', 'rating': 856}
1
{'name': 'Gerard Butler', 'rating': 665}
2
{'name': 'Emily Watson', 'rating': 553}
3
{'name': 'Greg Kinnear', 'rating': 459}
4
{'name': 'Mia Kirshner', 'rating': 561}
5
{'name': 'Jason Clarke', 'rating': 515}
6
{'name': 'Anton Yelchin', 'rating': 656}
7
{'name': 'Jack Nicholson', 'rating': 517}
8
{'name': 'James Cameron', 'rating': 534}
9
{'name': 'Ian McKellen', 'rating': 532}
10
{'name': 'Joseph Gordon-Levitt', 'rating': 533}
11
{'name': 'Ornella Muti', 'rating': 488}
12
{'name': 'Bridget Fonda', 'rating': 486}
13
{'name': 'John Leguizamo', 'rating': 543}
14
{'name': 'Lucy Liu', 'rating': 1046}
15
{'name': 'Amy Poehler', 'rating': 530}
16
{'name': 'Malcolm McDowell', 'rating': 494}
17
{'name': 'Shelley Winters', 'rating': 479}
18
{'name': 'Carice van Houten', 'rating': 924}
19
{'name': 'Christopher Lambert', 'rating': 466}
20
{'name': 'Rutger Hauer', 'rating': 472}
21
{'name': 'Leonardo DiCaprio', 'rating': 624}
22
{'name': 'Keira Knightley', 

{'name': 'Al Pacino', 'rating': 666}
190
{'name': 'Richard Gere', 'rating': 873}
191
{'name': 'Claire Danes', 'rating': 616}
192
{'name': 'Leslie Bibb', 'rating': 481}
193
{'name': 'Lea Thompson', 'rating': 528}
194
{'name': 'Sebastian Stan', 'rating': 492}
195
{'name': 'Steve Martin', 'rating': 461}
196
{'name': 'Ian Somerhalder', 'rating': 461}
197
{'name': "Vincent D'Onofrio", 'rating': 569}
198
{'name': 'Carly Chaikin', 'rating': 457}
199
{'name': 'Jamie Foxx', 'rating': 537}
200
{'name': 'Renée Zellweger', 'rating': 460}
201
{'name': 'Robert Swenson', 'rating': 567}
202
{'name': 'Matthew Lillard', 'rating': 461}
203
{'name': 'Julia Stiles', 'rating': 734}
204
{'name': 'Famke Janssen', 'rating': 466}
205
{'name': 'Ron Howard', 'rating': 488}
206
{'name': 'Chris Pratt', 'rating': 882}
207
{'name': 'Pam Grier', 'rating': 522}
208
{'name': 'Cara Delevingne', 'rating': 537}
209
{'name': 'John Malkovich', 'rating': 700}
210
{'name': 'Ray Liotta', 'rating': 524}
211
{'name': 'Rachelle Le

{'name': 'Alexandra Daddario', 'rating': 1056}
374
{'name': 'Robert Duvall', 'rating': 490}
375
{'name': 'Amy Adams', 'rating': 960}
376
{'name': 'Jim Broadbent', 'rating': 509}
377
{'name': 'Kristanna Loken', 'rating': 592}
378
{'name': 'Richard Harris', 'rating': 459}
379
{'name': 'Hayden Christensen', 'rating': 698}
380
{'name': 'Daniel Craig', 'rating': 643}
381
{'name': 'Bruce Willis', 'rating': 747}
382
{'name': 'Richard Madden', 'rating': 582}
383
{'name': 'Melissa McCarthy', 'rating': 471}
384
{'name': 'Eddie Murphy', 'rating': 592}
385
{'name': 'Adam Sandler', 'rating': 971}
386
{'name': 'Chris Evans', 'rating': 947}
387
{'name': 'Liana Liberato', 'rating': 596}
388
{'name': 'Jodie Foster', 'rating': 523}
389
{'name': 'Louis C.K.', 'rating': 507}
390
{'name': 'Lucy Hale', 'rating': 617}
391
{'name': "Maureen O'Hara", 'rating': 492}
392
{'name': 'Ashton Kutcher', 'rating': 462}
393
{'name': 'Mads Mikkelsen', 'rating': 494}
394
{'name': 'Sam Worthington', 'rating': 553}
395
{'na

In [6]:
data.head()

title  \
0  Percy Jackson & the Olympians: The Lightning T...   
1                                        Please Give   
2                                                 10   
3                    12 Angry Men (Twelve Angry Men)   
4                       20,000 Leagues Under The Sea   

                                               genre          directors  \
0  Action & Adventure, Comedy, Drama, Science Fic...     Chris Columbus   
1                                             Comedy  Nicole Holofcener   
2                                    Comedy, Romance      Blake Edwards   
3                                    Classics, Drama       Sidney Lumet   
4           Action & Adventure, Drama, Kids & Family  Richard Fleischer   

             writers                                             actors  \
0       Craig Titley  Logan Lerman, Brandon T. Jackson, Alexandra Da...   
1  Nicole Holofcener  Catherine Keener, Amanda Peet, Oliver Platt, R...   
2      Blake Edwards  Dudley Moore, Bo Derek, Julie Andrews, Robert ...   
3      Reginald Rose  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   
4        Earl Felton  James Mason, Kirk Douglas, Paul Lukas, Peter L...   

              studio_name  tomato_rating  audience_rating  
0        20th Century Fox             49             53.0  
1  Sony Pictures Classics             86             64.0  
2             Waner Bros.             68             53.0  
3    Criterion Collection            100             97.0  
4                  Disney             89             74.0

In [7]:
uniqueValues = df_final['studio_name'].unique().tolist()
uniqueValues[0]

for i in range(len(df_final)):
    df_final['studio_name'].iloc[i] = uniqueValues.index(df_final['studio_name'].iloc[i])

C:\Users\drago\Anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [8]:
df_final.head()

title  \
0  Percy Jackson & the Olympians: The Lightning T...   
1                                        Please Give   
2                                       3:10 to Yuma   
3                                       3:10 to Yuma   
4                                         Dark Water   

                                               genre          directors  \
0  Action & Adventure, Comedy, Drama, Science Fic...     Chris Columbus   
1                                             Comedy  Nicole Holofcener   
2                           Classics, Drama, Western       Delmer Daves   
3                 Action & Adventure, Drama, Western      James Mangold   
4  Art House & International, Horror, Mystery & S...       Hideo Nakata   

                                             writers  \
0                                       Craig Titley   
1                                  Nicole Holofcener   
2                                     Halsted Welles   
3         Derek Haas, Halsted Welles, Michael Brandt   
4  Hideo Hakata, Takashige Ichise, Yoshihiro Naka...   

                                              actors studio_name  \
0  Logan Lerman, Brandon T. Jackson, Alexandra Da...           0   
1  Catherine Keener, Amanda Peet, Oliver Platt, R...           1   
2  Glenn Ford, Van Heflin, Felicia Farr, Leora Da...           2   
3  Russell Crowe, Christian Bale, Logan Lerman, D...           3   
4  Hitomi Kuroki, Rio Kanno, Shigemitsu Ogi, Mire...           4   

   tomato_rating  audience_rating    budget  \
0             49             53.0  95000000   
1             86             64.0   3000000   
2             96             78.0  55000000   
3             89             86.0  55000000   
4             80             66.0  30000000   

                                              genres  
0  [{"id": 12, "name": "Adventure"}, {"id": 14, "...  
1  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...  
2                    [{"id": 37, "name": "Western"}]  
3                    [{"id": 37, "name": "Western"}]  
4  [{"id": 18, "name": "Drama"}, {"id": 27, "name...

In [9]:
uniqueValues = df_final['studio_name'].unique()
uniqueValues.shape

(547,)

In [10]:
actorsList
actorsAndRating[0]['rating']
dfActorsAndRating = pd.DataFrame(actorsAndRating)

dfActorsAndRating
# for i in range(len(actorsList)):
#     try:
#         for j in range(len(actorsList[i])):
#             if(actorsList[i] == actorsAndRating[j]['name']):
#                 listOfRatingFilm.append(actorsAndRating[j]['rating'])
#     except KeyError:
#         continue

for i in range(len(df_final)):
    temp = df_final['actors'].iloc[i].split(', ')
    sumAct = 0
    counter = 0
 #   print(temp)
    for j in range(len(temp)):
        if(len(dfActorsAndRating[dfActorsAndRating['name'] == temp[j]]) > 0):
            counter+=1
            sumAct = sumAct + dfActorsAndRating[dfActorsAndRating['name'] == temp[j]]['rating'].iloc[0]
    if(counter > 0):
        #print(sumAct/counter)
        df_final['actors'].iloc[i] = sumAct/counter
    else:
        df_final['actors'].iloc[i] = 0

        
df_final.head()

C:\Users\drago\Anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


title  \
0  Percy Jackson & the Olympians: The Lightning T...   
1                                        Please Give   
2                                       3:10 to Yuma   
3                                       3:10 to Yuma   
4                                         Dark Water   

                                               genre          directors  \
0  Action & Adventure, Comedy, Drama, Science Fic...     Chris Columbus   
1                                             Comedy  Nicole Holofcener   
2                           Classics, Drama, Western       Delmer Daves   
3                 Action & Adventure, Drama, Western      James Mangold   
4  Art House & International, Horror, Mystery & S...       Hideo Nakata   

                                             writers   actors studio_name  \
0                                       Craig Titley  647.667           0   
1                                  Nicole Holofcener    570.5           1   
2                                     Halsted Welles        0           2   
3         Derek Haas, Halsted Welles, Michael Brandt    760.5           3   
4  Hideo Hakata, Takashige Ichise, Yoshihiro Naka...        0           4   

   tomato_rating  audience_rating    budget  \
0             49             53.0  95000000   
1             86             64.0   3000000   
2             96             78.0  55000000   
3             89             86.0  55000000   
4             80             66.0  30000000   

                                              genres  
0  [{"id": 12, "name": "Adventure"}, {"id": 14, "...  
1  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...  
2                    [{"id": 37, "name": "Western"}]  
3                    [{"id": 37, "name": "Western"}]  
4  [{"id": 18, "name": "Drama"}, {"id": 27, "name...

In [11]:
import numpy as np

trainedSet = df_final.drop(columns=['title', 'genre', 'directors', 'writers', 'genres', 'tomato_rating'])
trainedSet = trainedSet[trainedSet['actors'] > 0]
trainedSet['budget'] = trainedSet['budget']/1000
#trainedSet = trainedSet.astype({'actors':'int64'})
trainedSet

actors studio_name  audience_rating   budget
0     647.667           0             53.0  95000.0
1       570.5           1             64.0   3000.0
3       760.5           3             86.0  55000.0
5       628.5           5             28.0  30000.0
6         640           6             64.0   9600.0
...       ...         ...              ...      ...
3915      766           2             41.0  80000.0
3916  698.375          20             80.0  28000.0
3917    668.5          20             20.0  50000.0
3918      585          80             33.0  35000.0
3919      809          20             91.0  16000.0

[2756 rows x 4 columns]

In [12]:
y = trainedSet['audience_rating']
X = trainedSet.drop(columns=['audience_rating'])

X = np.asarray(X)
y = np.asarray(y)

In [13]:
from sklearn.svm import SVR
import numpy as np


clf = SVR(C=5.0, epsilon=0.1, gamma='auto')
clf.fit(X, y)

SVR(C=5.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [14]:
pred = clf.predict(X[0:10]).round(1)
pred/10


array([5.7 , 6.39, 6.7 , 5.7 , 6.39, 5.7 , 5.71, 5.7 , 6.7 , 5.7 ])

In [15]:
y[0:10]/10

array([5.3, 6.4, 8.6, 2.8, 6.4, 3.5, 5.7, 4.7, 7.9, 5.2])

In [16]:
import tensorflow
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
import tensorflow.keras.optimizers 
#sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model = models.Sequential()
model.add(layers.Dense(2, activation = 'relu', input_shape = (3,)))
model.add(layers.Dense(1, activation = 'sigmoid'))

y = trainedSet['audience_rating']/100
y
X = trainedSet.drop(columns=['audience_rating'])
X = np.asarray(X)
y = np.asarray(y)
X


array([[647.6666666666666, 0, 95000.0],
       [570.5, 1, 3000.0],
       [760.5, 3, 55000.0],
       ...,
       [668.5, 20, 50000.0],
       [585.0, 80, 35000.0],
       [809.0, 20, 16000.0]], dtype=object)

In [17]:
model.compile(optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['acc'])

history_firstModel = model.fit(X, 
                    y,
                    epochs = 50, batch_size = 64)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.float64).

In [18]:

df_movies = pd.read_csv('tmdb_5000_movies.csv')
df_movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [19]:
df_movies = df_movies.drop(columns=['id', 'budget', 'overview','genres', 'homepage', 'keywords', 'original_language', 'original_title', 'production_countries','production_companies', 'release_date', 'spoken_languages', 'status', 'tagline'])

In [20]:
df_movies

popularity     revenue  runtime  \
0     150.437577  2787965087    162.0   
1     139.082615   961000000    169.0   
2     107.376788   880674609    148.0   
3     112.312950  1084939099    165.0   
4      43.926995   284139100    132.0   
...          ...         ...      ...   
4798   14.269792     2040920     81.0   
4799    0.642552           0     85.0   
4800    1.444476           0    120.0   
4801    0.857008           0     98.0   
4802    1.929883           0     90.0   

                                         title  vote_average  vote_count  
0                                       Avatar           7.2       11800  
1     Pirates of the Caribbean: At World's End           6.9        4500  
2                                      Spectre           6.3        4466  
3                        The Dark Knight Rises           7.6        9106  
4                                  John Carter           6.1        2124  
...                                        ...           ...         ...  
4798                               El Mariachi           6.6         238  
4799                                 Newlyweds           5.9           5  
4800                 Signed, Sealed, Delivered           7.0           6  
4801                          Shanghai Calling           5.7           7  
4802                         My Date with Drew           6.3          16  

[4803 rows x 6 columns]

In [21]:
dfs = [df_movies, df_final]
#merging the movies dataset with the budget dataset based on title
df_movies_final = reduce(lambda left,right: pd.merge(left,right,on='title'), dfs)

In [22]:
df_movies_final.head()

popularity     revenue  runtime                  title  vote_average  \
0  150.437577  2787965087    162.0                 Avatar           7.2   
1  107.376788   880674609    148.0                Spectre           6.3   
2  112.312950  1084939099    165.0  The Dark Knight Rises           7.6   
3   43.926995   284139100    132.0            John Carter           6.1   
4  115.699814   890871626    139.0           Spider-Man 3           5.9   

   vote_count                                              genre  \
0       11800  Action & Adventure, Comedy, Mystery & Suspense...   
1        4466                                 Action & Adventure   
2        9106      Action & Adventure, Drama, Mystery & Suspense   
3        2124  Action & Adventure, Horror, Kids & Family, Sci...   
4        3576  Action & Adventure, Mystery & Suspense, Scienc...   

                     directors  \
0                James Cameron   
1                   Sam Mendes   
2            Christopher Nolan   
3  Andrew Stanton, Mark Atkins   
4                    Sam Raimi   

                                             writers   actors studio_name  \
0                                      James Cameron   933.75           0   
1  Ian Fleming (II), John Logan, Neal Purvis, Rob...   1131.5          13   
2        Christopher Nolan, Jonathan Nolan, Bob Kane  840.875           8   
3  Mark Atkins, Mark Andrews, Michael Chabon, And...    551.5          26   
4     Alvin Sargent, Ivan Raimi, Sam Raimi, Stan Lee  671.667          13   

   tomato_rating  audience_rating     budget  \
0             82             82.0  237000000   
1             63             61.0  245000000   
2             87             90.0  250000000   
3             52             60.0  260000000   
4             63             51.0  258000000   

                                              genres  
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  
1  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  
2  [{"id": 28, "name": "Action"}, {"id": 80, "nam...  
3  [{"id": 28, "name": "Action"}, {"id": 12, "nam...  
4  [{"id": 14, "name": "Fantasy"}, {"id": 28, "na...

In [23]:
import numpy as np

trainedSet = df_movies_final.drop(columns=['title', 'genre', 'directors', 'writers', 'genres','studio_name','tomato_rating'])
trainedSet = trainedSet[trainedSet['actors'] > 0]
trainedSet = trainedSet[trainedSet['revenue'] > 0]
#trainedSet['budget'] = trainedSet['budget']/10000
#trainedSet['revenue'] = trainedSet['revenue']/10000
trainedSet = trainedSet.astype({'actors':'int64'})
trainedSet = trainedSet.astype({'popularity':'int64'})
trainedSet = trainedSet.astype({'revenue':'int64'})
trainedSet = trainedSet.astype({'runtime':'int64'})
trainedSet = trainedSet.astype({'vote_average':'int64'})
trainedSet = trainedSet.astype({'audience_rating':'int64'})
trainedSet = trainedSet.astype({'budget':'int64'})
trainedSet

popularity     revenue  runtime  vote_average  vote_count  actors  \
0            150  2787965087      162             7       11800     933   
1            107   880674609      148             6        4466    1131   
2            112  1084939099      165             7        9106     840   
3             43   284139100      132             6        2124     551   
4            115   890871626      139             5        3576     671   
...          ...         ...      ...           ...         ...     ...   
3763          33   100000000       93             6        1213     519   
3764          13     4505922       94             6         253     469   
3775           8     2891288       78             5          19     741   
3780          12     3200000       90             6         137     603   
3800          27      600896       95             5         631     571   

      audience_rating     budget  
0                  82  237000000  
1                  61  245000000  
2                  90  250000000  
3                  60  260000000  
4                  51  258000000  
...               ...        ...  
3763               70     400000  
3764               89     200000  
3775               57     150000  
3780               66     125000  
3800               38    4000000  

[2298 rows x 8 columns]

In [24]:
import tensorflow
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.optimizers import SGD
import tensorflow.keras.optimizers 
#sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model = models.Sequential()
model.add(layers.Dense(2, activation = 'relu', input_shape = (7,)))
model.add(layers.Dense(1, activation = 'sigmoid'))
pd.options.display.float_format = '{:.4f}'.format

y = trainedSet['audience_rating']
y
X = trainedSet.drop(columns=['audience_rating'])
X = np.asarray(X)
y = np.asarray(y)
X

array([[       150, 2787965087,        162, ...,      11800,        933,
         237000000],
       [       107,  880674609,        148, ...,       4466,       1131,
         245000000],
       [       112, 1084939099,        165, ...,       9106,        840,
         250000000],
       ...,
       [         8,    2891288,         78, ...,         19,        741,
            150000],
       [        12,    3200000,         90, ...,        137,        603,
            125000],
       [        27,     600896,         95, ...,        631,        571,
           4000000]], dtype=int64)

In [25]:
model.compile(optimizer = 'Adam',
              loss = 'binary_crossentropy',
              metrics = ['acc'])

history_firstModel = model.fit(X, 
                    y,
                    epochs = 100, batch_size = 64)

Train on 2298 samples
Epoch 1/100
2298/2298 [==============================] - 2s 701us/sample - loss: -7641932182.8372 - acc: 0.0000e+00
Epoch 2/100
2298/2298 [==============================] - 0s 15us/sample - loss: -8355849142.0296 - acc: 0.0000e+00
Epoch 3/100
2298/2298 [==============================] - 0s 15us/sample - loss: -9111218159.5126 - acc: 0.0000e+00
Epoch 4/100
2298/2298 [==============================] - 0s 16us/sample - loss: -9919722168.0348 - acc: 0.0000e+00
Epoch 5/100
2298/2298 [==============================] - 0s 14us/sample - loss: -10770517729.9217 - acc: 0.0000e+00
Epoch 6/100
2298/2298 [==============================] - 0s 14us/sample - loss: -11678199175.2411 - acc: 0.0000e+00
Epoch 7/100
2298/2298 [==============================] - 0s 15us/sample - loss: -12642345948.3516 - acc: 0.0000e+00
Epoch 8/100
2298/2298 [==============================] - 0s 16us/sample - loss: -13652569668.1775 - acc: 0.0000e+00
Epoch 9/100
2298/2298 [==============================

2298/2298 [==============================] - 0s 13us/sample - loss: -184866657992.0766 - acc: 0.0000e+00
Epoch 71/100
2298/2298 [==============================] - 0s 13us/sample - loss: -189215758394.8199 - acc: 0.0000e+00
Epoch 72/100
2298/2298 [==============================] - 0s 15us/sample - loss: -193595499002.2071 - acc: 0.0000e+00
Epoch 73/100
2298/2298 [==============================] - 0s 13us/sample - loss: -198023566577.5179 - acc: 0.0000e+00
Epoch 74/100
2298/2298 [==============================] - 0s 14us/sample - loss: -202496546361.4830 - acc: 0.0000e+00
Epoch 75/100
2298/2298 [==============================] - 0s 14us/sample - loss: -206996664523.1958 - acc: 0.0000e+00
Epoch 76/100
2298/2298 [==============================] - 0s 15us/sample - loss: -211570237661.0200 - acc: 0.0000e+00
Epoch 77/100
2298/2298 [==============================] - 0s 13us/sample - loss: -216168264439.3107 - acc: 0.0000e+00
Epoch 78/100
2298/2298 [==============================] - 0s 13us/sam

In [26]:
model.predict(X[0:10])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [27]:
y[0:10]

array([82, 61, 90, 60, 51, 87, 83, 78, 63, 61], dtype=int64)

In [28]:
y = trainedSet['popularity']
y
X = trainedSet.drop(columns=['popularity'])
X = np.asarray(X)
y = np.asarray(y)

In [29]:
from sklearn.svm import SVR
import numpy as np


clf = SVR(C=1.0, epsilon=0.1, gamma='auto')
clf.fit(X, y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [30]:
pred = clf.predict(X[0:10]).round(1)
pred

array([24.3, 24.3, 24.3, 24.3, 24.3, 24.3, 24.3, 24.3, 24.3, 24.3])

In [31]:
y[0:10]

array([150, 107, 112,  43, 115,  48, 134,  98, 155,  57], dtype=int64)